# Generated by Django 4.1.6 on 2023-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite')], max_length=50),
        ),
    ]
