# Generated by Django 4.1.6 on 2023-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
    ]
