# Generated by Django 4.1.6 on 2023-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_company_logo_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo_url',
            field=models.URLField(default='https://res.cloudinary.com/dvzbsqkfs/image/upload/v1675945846/workforce_assessment/media/company_logos/logo_speksk.png', max_length=300),
        ),
    ]
